/**
*Createdbyi50406on12/3/2015.
*/
intro();
ControlPoints();
CancellationComment();
ControlPoint1();
cpNotes();
ThirdPartyURL();
Contacts();
mortgageMain();
addressesMain();
contactMethodsPhone();
contactMethodsEmail();
CompanyAddresses();
companyMain();
companyMainAddress();
projectInfo();
lossInfo();
adminInfo();
insuranceClient();
ICAddresses();
ICPhone();
ICEmail();
assignmentReferral();
billingArrangement();
adm();
subrogationNote();
coverageLoss();
coverageNote();
coveragesMain();
coverage();
subLimits();
typeOfLoss();
causeOfLoss();
Forms();
params();
